commands-aliases:
  itemskins:
    - "itemskin"
    - "is"
    - "iskins"

# Configuration Explanation
# (options)
#   (remove-skin-no-permission) Should we remove item skins if the player doesn't have permission to use that skin?
options:
  remove-skin-no-permission: false

# The skin remover item details
skin-remover:
  material: LEATHER
  customModelData: 7608
  display-name: "&eSkin Remover"
  glowing: false
  lore:
    - "&7Drag & Drop this item to the"
    - "&7item that has skin!"

messages:
  prefix: "&e[Skins]"
  noPermission: "{prefix} &cYou don't have enough permission!"
  reload: "{prefix} &aYou have reloaded the configuration!"
  playerNotFound: "{prefix} &cThe player is not online!"
  mustInt: "{prefix} &cThe amount must be a number/integer!"
  materialNotFound: "{prefix} &cThere is no skin with that material!"
  skinNotFound: "{prefix} &cThere is no skin with that name!"
  itemHasSkin: "{prefix} &cThat item already have a skin!"
  itemNoSkin: "{prefix} &cThat item doesn't have any skin!"
  help:
    - "&e&lItemSkins &7- by aglerr"
    - "&e/itemskins reload &7- reload the configuration"
    - "&e/itemskins physical (player) (material) (skin-name) [amount]"
    - "&e/itemskins remover (player) [amount]"
    - "&e/skins &7- open skin selector inventory"